version: '3.8'

volumes:
  test_bulma_data:
    name: test_bulma_data

services:
  mongo:
    image: mongo
    container_name: test_bulma_db
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '27017:27017'


 