name: Build Docker Migrate Image CI
on:
  push:
    branches: [ "migrate" ]

jobs:

  build-docker-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker Migrate image
      run: docker build -t migrate-be .
    - name:  Tag image
      run: docker tag migrate-be manhndtest/huni-migrate-be
    - name: Login docker
      env:
        PASSWORD: ${{secrets.DOCKER_PWD}}
      run: docker login -u manhndtest -p "$PASSWORD"
    - name: Push to dockerhub
      run: docker push manhndtest/huni-migrate-be
